trigger:
  - master

variables:
  buildConfiguration: "Release"
  dotNetFramework: "net7.0"
  dotNetVersion: "7.0.x"
  targetRuntime: "win-x86"

pool:
  vmImage: windows-latest

steps:
  - template: build-WEB.yml
  - task: DotNetCoreCLI@2
    inputs:
      command: "publish"
      publishWebProjects: false
      projects: "**/Delivery.Web.App.csproj"
      arguments: "--configuration $(BuildConfiguration) --framework $(dotNetFramework) --output $(Build.ArtifactStagingDirectory)/web --self-contained true -r $(targetRuntime)"
      modifyOutputPath: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)/web"
      ArtifactName: "WEB"
      publishLocation: "Container"
